/**
 * Meeting Notes Generator Service
 * Auto-generates meeting notes from RFP discussions and progress
 */

import { generateAIResponse } from './aiService';

/**
 * Generate meeting notes from RFP project data
 * @param {object} project - The RFP project data
 * @param {string} meetingType - Type of meeting (kickoff, progress, review, handoff)
 * @param {array} attendees - List of attendees
 * @param {object} options - Additional options
 */
export const generateMeetingNotes = async (project, meetingType = 'progress', attendees = [], options = {}) => {
    try {
        // Calculate project stats
        const totalQuestions = project.sections?.reduce((sum, s) => sum + (s.questions?.length || 0), 0) || 0;
        const answeredQuestions = project.sections?.reduce((sum, s) =>
            sum + (s.questions?.filter(q => q.answer)?.length || 0), 0) || 0;
        const approvedQuestions = project.sections?.reduce((sum, s) =>
            sum + (s.questions?.filter(q => q.status === 'approved' || q.status === 'final')?.length || 0), 0) || 0;
        const completionPercent = totalQuestions > 0 ? Math.round((answeredQuestions / totalQuestions) * 100) : 0;

        const meetingTemplates = {
            kickoff: 'RFP Kickoff Meeting - Initial review and assignments',
            progress: 'RFP Progress Update - Status check and blockers',
            review: 'RFP Review Meeting - Quality review and approvals',
            handoff: 'RFP Handoff Meeting - Final review before submission'
        };

        const prompt = `Generate professional meeting notes for an RFP project meeting.

Meeting Type: ${meetingTemplates[meetingType] || 'RFP Meeting'}
Date: ${new Date().toLocaleDateString()}
Project: ${project.name || 'Untitled RFP'}
Client: ${project.client || 'Not specified'}

Attendees: ${attendees.length > 0 ? attendees.join(', ') : 'Team members'}

Project Status:
- Total Questions: ${totalQuestions}
- Answered: ${answeredQuestions} (${completionPercent}%)
- Approved: ${approvedQuestions}
- Due Date: ${project.dueDate ? new Date(project.dueDate).toLocaleDateString() : 'Not set'}
- Priority: ${project.priority || 'Normal'}

${options.additionalContext ? `Additional Context: ${options.additionalContext}` : ''}

Generate meeting notes with the following sections:
1. Meeting Summary (2-3 sentences)
2. Key Discussion Points (3-5 bullet points)
3. Decisions Made (if any)
4. Action Items (with owners if attendees provided)
5. Next Steps
6. Next Meeting (suggested date/focus)

Keep it concise and professional. Format in Markdown.`;

        const result = await generateAIResponse({
            questionText: prompt,
            actionType: 'generate'
        });

        const notes = result.text || result.response || `# ${meetingTemplates[meetingType] || 'RFP Meeting Notes'}

## Meeting Summary
Progress meeting for ${project.name || 'RFP Project'} held on ${new Date().toLocaleDateString()}.

## Project Status
- Total Questions: ${totalQuestions}
- Answered: ${answeredQuestions} (${completionPercent}%)
- Approved: ${approvedQuestions}

## Key Discussion Points
- Review current progress and blockers
- Discuss upcoming deadlines
- Assign remaining questions

## Action Items
- Continue answering remaining questions
- Review completed responses
- Prepare for final submission

## Next Steps
Focus on completing high-priority sections before deadline.`;

        return {
            success: true,
            notes,
            metadata: {
                projectId: project.id,
                projectName: project.name,
                meetingType,
                generatedAt: new Date().toISOString(),
                stats: {
                    totalQuestions,
                    answeredQuestions,
                    approvedQuestions,
                    completionPercent
                }
            }
        };
    } catch (error) {
        console.error('Error generating meeting notes:', error);
        // Return fallback notes on error
        const totalQuestions = project.sections?.reduce((sum, s) => sum + (s.questions?.length || 0), 0) || 0;
        const answeredQuestions = project.sections?.reduce((sum, s) =>
            sum + (s.questions?.filter(q => q.answer)?.length || 0), 0) || 0;

        return {
            success: true,
            notes: `# RFP Progress Meeting Notes

**Project:** ${project.name || 'Untitled RFP'}
**Date:** ${new Date().toLocaleDateString()}

## Status
- Questions: ${answeredQuestions}/${totalQuestions} completed
- Due: ${project.dueDate ? new Date(project.dueDate).toLocaleDateString() : 'TBD'}

## Action Items
- Continue working on remaining questions
- Schedule next review session

---
*Generated by RFPgrep*`,
            metadata: {
                projectId: project.id,
                meetingType,
                generatedAt: new Date().toISOString()
            }
        };
    }
};

/**
 * Generate kickoff meeting agenda
 */
export const generateKickoffAgenda = async (project) => {
    try {
        const totalQuestions = project.sections?.reduce((sum, s) => sum + (s.questions?.length || 0), 0) || 0;

        const prompt = `Generate a kickoff meeting agenda for an RFP project.

Project: ${project.name || 'New RFP'}
Client: ${project.client || 'Not specified'}
Questions: ${totalQuestions}
Due Date: ${project.dueDate ? new Date(project.dueDate).toLocaleDateString() : 'TBD'}

Create a 30-minute kickoff agenda with time allocations. Include:
1. Project Overview
2. Team Roles
3. Timeline Review
4. Question Assignment Strategy
5. Q&A

Format in Markdown with time allocations.`;

        const result = await generateAIResponse({
            questionText: prompt,
            actionType: 'generate'
        });

        return {
            success: true,
            agenda: result.text || result.response || `# Kickoff Agenda - ${project.name}\n\n1. Overview (5 min)\n2. Roles (5 min)\n3. Timeline (10 min)\n4. Assignments (5 min)\n5. Q&A (5 min)`
        };
    } catch (error) {
        console.error('Error generating agenda:', error);
        return {
            success: true,
            agenda: `# Kickoff Agenda\n\n1. Overview (5 min)\n2. Roles (5 min)\n3. Timeline (10 min)\n4. Assignments (5 min)\n5. Q&A (5 min)`
        };
    }
};

/**
 * Generate status report for stakeholders
 */
export const generateStatusReport = async (project) => {
    try {
        const totalQuestions = project.sections?.reduce((sum, s) => sum + (s.questions?.length || 0), 0) || 0;
        const answeredQuestions = project.sections?.reduce((sum, s) =>
            sum + (s.questions?.filter(q => q.answer)?.length || 0), 0) || 0;
        const percent = totalQuestions > 0 ? Math.round((answeredQuestions / totalQuestions) * 100) : 0;

        const prompt = `Generate a brief executive status report for an RFP project.

Project: ${project.name}
Client: ${project.client || 'N/A'}
Progress: ${answeredQuestions}/${totalQuestions} questions (${percent}%)
Due: ${project.dueDate ? new Date(project.dueDate).toLocaleDateString() : 'TBD'}
Status: ${project.outcome || 'In Progress'}

Generate a 3-paragraph executive summary covering:
1. Current status and progress
2. Key achievements and blockers
3. Next steps and timeline

Keep it concise and suitable for stakeholders.`;

        const result = await generateAIResponse({
            questionText: prompt,
            actionType: 'generate'
        });

        return {
            success: true,
            report: result.text || result.response || `## Status Report\n\nProgress: ${percent}% complete (${answeredQuestions}/${totalQuestions} questions answered).`
        };
    } catch (error) {
        console.error('Error generating status report:', error);
        return {
            success: true,
            report: `## Status Report\n\nProject is in progress. Continuing work on remaining questions.`
        };
    }
};

export default {
    generateMeetingNotes,
    generateKickoffAgenda,
    generateStatusReport
};
